/* Proteomics 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  proteomics: {
    label: "Proteomics 互動考題",
    label_en: "Proteomics Interactive Quiz",
    labels_en: {
      "核心分析流程": "Core MS-Based Pipeline",
      "進階分析主題": "Advanced Topics",
      "Step 1：樣品製備 (Sample Prep)": "Step 1: Sample Preparation",
      "Step 2：LC-MS/MS 採集": "Step 2: LC-MS/MS Acquisition",
      "Step 3：資料庫搜尋與鑑定 (ID)": "Step 3: Search & Identification",
      "Step 4：定量策略 (Quantification)": "Step 4: Quantification",
      "Step 5：品質管控 (QC)": "Step 5: Quality Control",
      "Step 6：標準化 (Normalization)": "Step 6: Normalization",
      "Step 7：缺失值處理 (Imputation)": "Step 7: Missing Value Imputation",
      "Step 8：差異表達分析 (DE)": "Step 8: Differential Expression",
      "Step 9：功能富集分析 (Enrichment)": "Step 9: Functional Enrichment",
      "Advanced：PTM 修飾分析": "Advanced: PTM Analysis",
      "Advanced：靶向蛋白質體學 (Targeted)": "Advanced: Targeted Proteomics",
      "Advanced：Top-down 完整蛋白質": "Advanced: Top-down Proteomics",
      "Advanced：空間蛋白質體學 (Spatial)": "Advanced: Spatial Proteomics",
      "Advanced：單細胞蛋白質體學": "Advanced: Single-cell Proteomics",
      "Advanced：親合性蛋白質體學 (Affinity)": "Advanced: Affinity Proteomics"
    },
    subjects: {
      "核心分析流程": {
        "Step 1：樣品製備 (Sample Prep)": [
          { type:"single",
            stem:"在 bottom-up proteomics 中，最常用的酵素消化試劑為何？",
            stem_en:"What is the most commonly used enzyme for digestion in bottom-up proteomics?",
            A:"Chymotrypsin", A_en:"Chymotrypsin",
            B:"Trypsin（在 K/R 後切割，除非後面是 P）", B_en:"Trypsin (cleaves after K/R, except when followed by P)",
            C:"Pepsin", C_en:"Pepsin",
            D:"Lysozyme", D_en:"Lysozyme",
            ans:"B",
            exp:"Trypsin 是 bottom-up proteomics 的黃金標準，特異性高、切割後產生適合 MS/MS 分析的胜肽長度（7–30 aa）且 C 端為帶正電 K/R 利於離子化。",
            exp_en:"Trypsin is the bottom-up gold standard: high specificity, ideal MS/MS peptide length (7–30 aa), and C-terminal K/R provides positive charge for ionization." },
          { type:"single",
            stem:"還原烷化步驟中使用 IAA (iodoacetamide)，為何必須在暗處進行？",
            stem_en:"Why must the alkylation step with IAA (iodoacetamide) be performed in the dark?",
            A:"光照會破壞 IAA 結構", A_en:"Light destroys IAA structure",
            B:"光照促進 IAA 與 Met、His、Lys 等發生非特異性烷化，造成假陽性 +57 偏移", B_en:"Light promotes non-specific alkylation of Met/His/Lys, causing spurious +57 modifications",
            C:"DTT 在光下失活", C_en:"DTT loses activity under light",
            D:"純粹是實驗室慣例，無實際意義", D_en:"Purely a lab convention with no real basis",
            ans:"B",
            exp:"IAA 光照下會反應更廣泛，造成 Met、His、Lys 上的非特異性烷化，這會在 search 時被誤認為 PTM (+57 Da)。",
            exp_en:"Under light, IAA reacts more broadly, alkylating Met/His/Lys non-specifically — these spurious +57 Da additions look like real PTMs in search results." },
          { type:"single",
            stem:"你有 10 mg 冷凍肝組織，預期含大量膜蛋白與少量結締組織。最適合的樣品製備策略？",
            stem_en:"You have 10 mg frozen liver tissue with abundant membrane proteins. Best prep approach?",
            A:"In-solution + 0.1% RapiGest", A_en:"In-solution + 0.1% RapiGest",
            B:"FASP（強迫使用 1% SDS）", B_en:"FASP (with 1% SDS)",
            C:"S-Trap 搭配 5% SDS 裂解（最能溶解膜蛋白）", C_en:"S-Trap with 5% SDS (best for solubilizing membrane proteins)",
            D:"完全省略 detergent", D_en:"Skip detergent entirely",
            ans:"C",
            exp:"S-Trap 能容忍高達 5% 的 SDS，是少數能直接處理高 SDS 樣品的方法，對膜蛋白覆蓋率極佳。",
            exp_en:"S-Trap tolerates up to 5% SDS — one of the few methods compatible with such high-detergent samples — and excels for membrane proteins." },
          { type:"multi",
            stem:"下列哪些是常用的蛋白質純化／消化方法？（多選）",
            stem_en:"Which of the following are common protein purification/digestion methods? (Multiple)",
            A:"FASP (Filter-Aided Sample Preparation)", A_en:"FASP (Filter-Aided Sample Preparation)",
            B:"SP3（磁珠法）", B_en:"SP3 (magnetic bead-based)",
            C:"S-Trap（懸浮捕獲）", C_en:"S-Trap (suspension trap)",
            D:"Northern Blot", D_en:"Northern Blot",
            ans:["A","B","C"],
            exp:"D 是 RNA 偵測方法，與蛋白質製備無關。",
            exp_en:"D is an RNA detection method, unrelated to protein prep." },
          { type:"tf",
            stem:"是非題：高 missed cleavage rate（如 45%）通常代表消化效率不佳，應增加酵素比例或延長時間。",
            stem_en:"True/False: A high missed cleavage rate (e.g., 45%) usually indicates incomplete digestion; raise enzyme ratio or extend time.",
            ans:"T",
            exp:"理想 missed cleavage 應 < 25%；過高代表酵素活性或時間不足，建議增加 trypsin 比例（如 1:25）或加入 Lys-C 預消化。",
            exp_en:"Ideal missed cleavage is < 25%; high rates mean insufficient enzyme or time. Increase trypsin ratio (e.g., 1:25) or add Lys-C pre-digestion." },
          { type:"single",
            stem:"SP3（Single-Pot Solid-Phase-enhanced Sample Preparation）的核心原理為何？",
            stem_en:"What is the core principle of SP3 (Single-Pot Solid-Phase-enhanced Sample Preparation)?",
            A:"使用 10 kDa MWCO 濾膜離心過濾", A_en:"Uses a 10 kDa MWCO spin filter",
            B:"在 50% 乙醇環境下，carboxylate 磁珠捕獲變性蛋白；洗去清潔劑後在珠上消化", B_en:"At 50% ethanol, carboxylate-modified magnetic beads bind denatured proteins; detergents are washed off and digestion proceeds on-bead",
            C:"沉澱蛋白後用 acetone 重溶", C_en:"Precipitates proteins and redissolves in acetone",
            D:"使用抗體富集特定蛋白", D_en:"Uses antibody enrichment for specific proteins",
            ans:"B",
            exp:"SP3 利用蛋白在有機溶劑中容易與磁珠表面非特異結合的特性，將其捕獲、洗滌、最後在珠上消化，是 2024-25 最受歡迎的低量樣品製備法。",
            exp_en:"SP3 exploits non-specific protein binding to carboxylate beads in organic solvent — capture, wash, on-bead digest. The most popular low-input prep method in 2024-25." },
          { type:"single",
            stem:"血漿樣品的蛋白質體學分析前，為什麼通常要先做「top-12 蛋白移除」？",
            stem_en:"Why is 'top-12 protein depletion' typically required before plasma proteomics?",
            A:"純粹為了減少樣品體積", A_en:"Merely to reduce sample volume",
            B:"Albumin 與 IgG 等高豐度蛋白佔總蛋白的 80%+，會壓抑低豐度生物標誌物的偵測", B_en:"Albumin, IgG and other top-abundant proteins make up 80%+ of plasma protein, suppressing detection of low-abundance biomarkers",
            C:"這些蛋白會破壞質譜儀", C_en:"They damage the MS instrument",
            D:"它們含 PTM 太多", D_en:"They carry too many PTMs",
            ans:"B",
            exp:"血漿蛋白動態範圍跨 10+ 個數量級；不移除 top-abundant 蛋白，低豐度蛋白（cytokine、hormone）無法被偵測。",
            exp_en:"Plasma protein dynamic range spans 10+ orders; without removing top-abundant proteins, low-abundance proteins (cytokines, hormones) won't be detected." },
          { type:"multi",
            stem:"以下哪些變性試劑/條件可用於 bottom-up 樣品的蛋白裂解？（多選）",
            stem_en:"Which of the following denaturing agents/conditions can be used for bottom-up sample lysis? (Multiple)",
            A:"5% SDS", A_en:"5% SDS",
            B:"8 M urea", B_en:"8 M urea",
            C:"6 M guanidine HCl", C_en:"6 M guanidine HCl",
            D:"純水 (pure water)", D_en:"Pure water",
            ans:["A","B","C"],
            exp:"純水無變性能力，無法有效裂解細胞釋放蛋白。",
            exp_en:"Pure water lacks denaturing power and cannot effectively lyse cells to release proteins." }
        ],
        "Step 2：LC-MS/MS 採集": [
          { type:"single",
            stem:"DDA (Data-Dependent Acquisition) 的核心特徵為何？",
            stem_en:"What is the core feature of DDA (Data-Dependent Acquisition)?",
            A:"先做 MS1 全掃描，依強度選擇 Top-N 母離子做 MS2，每次只碎裂單一母離子", A_en:"After MS1 scan, select Top-N most intense precursors and fragment each individually",
            B:"在固定 m/z 窗口內無差別碎裂所有離子", B_en:"Fragment everything within fixed m/z windows",
            C:"只掃描 MS1，不做 MS2", C_en:"Only MS1 scans, no MS2",
            D:"從蛋白序列預測 fragment 後直接定量", D_en:"Predicts fragments from sequences and quantifies directly",
            ans:"A",
            exp:"DDA 是「選強者而戰」——先 MS1 看母離子強度，挑 Top-N 各別做 MS2，產生 clean spectra 但有 stochastic missing 問題。",
            exp_en:"DDA is 'pick the strongest' — MS1 identifies precursors, Top-N each get clean MS2 spectra, but stochastic missing is the downside." },
          { type:"single",
            stem:"DIA (Data-Independent Acquisition) 相對 DDA 的最大優勢為何？",
            stem_en:"DIA's biggest advantage over DDA?",
            A:"取得更乾淨的 MS2 譜", A_en:"Cleaner MS2 spectra",
            B:"近乎完整的定量矩陣（&lt; 5% missing），極佳的 run-to-run 重現性", B_en:"Near-complete quantitation matrix (< 5% missing), excellent run-to-run reproducibility",
            C:"完全不需 LC", C_en:"No LC required at all",
            D:"自動鑑定 PTM", D_en:"Auto-identifies PTMs",
            ans:"B",
            exp:"DIA 在預先定義窗口內碎裂所有母離子，不存在 DDA 的隨機選擇缺失，極適合大規模 cohort 與臨床研究。",
            exp_en:"DIA fragments everything in pre-defined windows with no stochastic gaps — ideal for large cohorts and clinical studies." },
          { type:"single",
            stem:"DIA 採集中為何 MS2 譜是「混合譜」(chimeric)？",
            stem_en:"Why are DIA MS2 spectra 'chimeric'?",
            A:"DIA 解析度太低", A_en:"DIA resolution is too low",
            B:"在較寬的 m/z 窗口內同時碎裂多個共流出的母離子，所有 fragment 混在一張譜中", B_en:"Multiple co-eluting precursors within a wide m/z window are fragmented simultaneously, so all fragments appear in one mixed spectrum",
            C:"儀器故障", C_en:"Instrument malfunction",
            D:"DIA 無法產生 MS2", D_en:"DIA can't produce MS2",
            ans:"B",
            exp:"DIA 窗口寬（4–25 m/z），窗內共流出的多個 peptide 同時被碎裂，需用 spectral library 或 deep-learning（DIA-NN）解析混合譜。",
            exp_en:"DIA windows are wide (4–25 m/z); co-eluting peptides are fragmented together. Spectral libraries or deep learning (DIA-NN) deconvolute the chimeric spectra." },
          { type:"single",
            stem:"你需要分析 60 個臨床血漿樣品做差異表達，需要完整定量矩陣。最佳採集策略？",
            stem_en:"60 clinical plasma samples for DE analysis, need a complete quant matrix. Best strategy?",
            A:"Top-30 DDA，每樣品分別處理", A_en:"Top-30 DDA on each sample separately",
            B:"library-free DIA（DIA-NN directDIA）", B_en:"Library-free DIA (DIA-NN directDIA)",
            C:"Top-down，分析完整蛋白", C_en:"Top-down on intact proteins",
            D:"60-plex TMT 一次跑完", D_en:"60-plex TMT in one run",
            ans:"B",
            exp:"library-free DIA 提供近完整定量矩陣與優異重現性，是 cohort 規模研究 2024-25 主流策略。",
            exp_en:"Library-free DIA delivers a near-complete matrix with excellent reproducibility — the 2024-25 mainstream for cohort-scale studies." },
          { type:"single",
            stem:"diaPASEF 結合哪兩種技術？",
            stem_en:"diaPASEF combines which two technologies?",
            A:"TIMS (Trapped Ion Mobility) + DIA", A_en:"TIMS (Trapped Ion Mobility) + DIA",
            B:"Orbitrap + ETD", B_en:"Orbitrap + ETD",
            C:"FT-ICR + UVPD", C_en:"FT-ICR + UVPD",
            D:"MALDI + DDA", D_en:"MALDI + DDA",
            ans:"A",
            exp:"diaPASEF 將 Bruker 的 TIMS（離子遷移率分離）與 DIA 整合，提供第二維分離以區分共流出離子，特別適合 single-cell proteomics。",
            exp_en:"diaPASEF integrates Bruker's TIMS (ion mobility separation) with DIA — a second dimension to resolve co-eluting ions, ideal for single-cell proteomics." },
          { type:"multi",
            stem:"下列哪些是 2024-25 主流的高速質譜儀？（多選）",
            stem_en:"Which of the following are mainstream high-speed MS instruments in 2024-25? (Multiple)",
            A:"Orbitrap Astral", A_en:"Orbitrap Astral",
            B:"timsTOF Ultra / SCP", B_en:"timsTOF Ultra / SCP",
            C:"Orbitrap Exploris 480", C_en:"Orbitrap Exploris 480",
            D:"Compact 1980 sector field MS", D_en:"Compact 1980 sector field MS",
            ans:["A","B","C"],
            exp:"A、B、C 都是現代主流；D 是過時的舊型儀器。",
            exp_en:"A, B, C are modern mainstream instruments; D is obsolete." },
          { type:"tf",
            stem:"是非題：DDA 比 DIA 更適合單一探索性 PTM 研究（如新 phospho-site 發現）。",
            stem_en:"True/False: DDA is more suitable than DIA for exploratory PTM studies (e.g., novel phosphosite discovery).",
            ans:"T",
            exp:"DDA 產生乾淨單一胜肽 MS2 譜，搭配 open search（如 MSFragger）可發現未預期的 PTM；DIA 的混合譜對未知 PTM 較困難。",
            exp_en:"DDA produces clean single-peptide MS2 spectra; combined with open search (MSFragger), it can discover unexpected PTMs. DIA chimeric spectra make this harder." },
          { type:"single",
            stem:"什麼是 LC-MS/MS 的 nano-flow LC？",
            stem_en:"What is nano-flow LC in LC-MS/MS?",
            A:"超低流速（~300 nL/min）+ 細管徑 C18 柱，提升靈敏度", A_en:"Ultra-low flow rate (~300 nL/min) + narrow-bore C18 column, boosting sensitivity",
            B:"高流速（5 mL/min）的常規 HPLC", B_en:"Conventional high-flow HPLC at 5 mL/min",
            C:"完全無 LC，直接注射", C_en:"No LC, direct injection",
            D:"NMR 配合 LC", D_en:"NMR combined with LC",
            ans:"A",
            exp:"nano-flow LC 用 75 μm 內徑、25-50 cm 長 C18 反相柱，流速 ~300 nL/min；窄管+低流速顯著提升 ESI 效率與蛋白覆蓋。",
            exp_en:"nano-flow LC uses 75 μm × 25–50 cm C18 columns at ~300 nL/min; the narrow bore + low flow significantly improves ESI efficiency and proteome depth." }
        ],
        "Step 3：資料庫搜尋與鑑定 (ID)": [
          { type:"single",
            stem:"在 peptide-spectrum matching (PSM) 過程中，最關鍵的概念為何？",
            stem_en:"What is the key concept in peptide-spectrum matching (PSM)?",
            A:"實驗 MS2 與「資料庫經 in silico 消化所有理論胜肽的計算碎片譜」比對，最高分為 PSM", A_en:"Match experimental MS2 against theoretical spectra generated by in silico digestion of the database; the highest score = PSM",
            B:"純粹比對 MS1 強度", B_en:"Just compare MS1 intensities",
            C:"使用 AI 直接從原始 spectrum 生成蛋白序列", C_en:"Use AI to generate sequences directly from raw spectra",
            D:"比對 DNA 序列", D_en:"Compare DNA sequences",
            ans:"A",
            exp:"PSM 的核心是「實驗 MS2 譜」與「資料庫所有理論胜肽的計算譜」之間的相似度評分，最高分為「最佳猜測」。",
            exp_en:"PSM scores similarity between experimental MS2 and computed theoretical spectra from the digested database; the top score is the 'best guess'." },
          { type:"single",
            stem:"為何 search 需要 decoy database？",
            stem_en:"Why does a database search need a decoy database?",
            A:"加速搜尋", A_en:"Speed up the search",
            B:"提供「假陽性的基準線」，估計隨機匹配率以計算 FDR", B_en:"Provides the 'false-positive baseline' to estimate random match rate and compute FDR",
            C:"增加蛋白覆蓋率", C_en:"Increase protein coverage",
            D:"防止資料外洩", D_en:"Prevent data leakage",
            ans:"B",
            exp:"Decoy（反轉/亂序序列）匹配到的 PSM 必為假陽性，提供 FDR 統計的基準。",
            exp_en:"Matches to decoys (reversed/shuffled sequences) must be false; they provide the baseline for FDR statistics." },
          { type:"single",
            stem:"關於 FDR (False Discovery Rate) 控制，下列何者最正確？",
            stem_en:"Which statement about FDR control is most accurate?",
            A:"PSM-level FDR 自動套用到 protein-level", A_en:"PSM-level FDR automatically applies to protein-level",
            B:"PSM-level、peptide-level、protein-level FDR 必須獨立控制，三層都要檢驗", B_en:"PSM, peptide, and protein-level FDRs must each be controlled independently",
            C:"FDR 1% 意味全部 PSM 都是錯的", C_en:"1% FDR means all PSMs are wrong",
            D:"FDR 與蛋白質體學無關", D_en:"FDR is unrelated to proteomics",
            ans:"B",
            exp:"FDR 在不同層級會放大或縮小：論文常見的「1% FDR protein-level」並不等同 PSM-level 1%，三層都需要分別控制。",
            exp_en:"FDR doesn't propagate linearly across layers; '1% protein FDR' isn't the same as '1% PSM FDR'. All three need independent control." },
          { type:"single",
            stem:"下列哪個搜尋引擎是 2024-25 主流，以「fragment-index 預編索引」聞名於極高速度？",
            stem_en:"Which 2024-25 mainstream search engine is famous for ultrafast 'fragment-index' precomputation?",
            A:"Mascot 1.0", A_en:"Mascot 1.0",
            B:"MSFragger（FragPipe 套件）", B_en:"MSFragger (FragPipe suite)",
            C:"BLAST", C_en:"BLAST",
            D:"DIA-NN（僅用於 DIA）", D_en:"DIA-NN (DIA only)",
            ans:"B",
            exp:"MSFragger 透過 fragment-index 預編索引大幅加速 search，可在數小時內處理 100+ 樣品，是 FragPipe 核心引擎。",
            exp_en:"MSFragger's fragment-index precomputation enables 100+ sample processing in hours — it's the core engine of FragPipe." },
          { type:"multi",
            stem:"以下哪些工具是 DIA 資料分析的主流？（多選）",
            stem_en:"Which of the following are mainstream tools for DIA data analysis? (Multiple)",
            A:"DIA-NN", A_en:"DIA-NN",
            B:"Spectronaut", B_en:"Spectronaut",
            C:"FragPipe (MSFragger-DIA)", C_en:"FragPipe (MSFragger-DIA)",
            D:"Northern Blot", D_en:"Northern Blot",
            ans:["A","B","C"],
            exp:"A、B、C 都是主流 DIA 工具；D 是 RNA 偵測方法。",
            exp_en:"A, B, C are mainstream DIA tools; D is an RNA method." },
          { type:"single",
            stem:"Percolator 在 search 結果中的功能為何？",
            stem_en:"What does Percolator do in search post-processing?",
            A:"產生 fragment ions 的理論譜", A_en:"Generate theoretical fragment spectra",
            B:"半監督式 SVM 重新評分 PSM，提升靈敏度（可在固定 FDR 下增加識別數）", B_en:"Semi-supervised SVM rescoring of PSMs to boost sensitivity (more IDs at the same FDR)",
            C:"產生 spectral library", C_en:"Build spectral library",
            D:"執行 ANOVA 統計", D_en:"Run ANOVA",
            ans:"B",
            exp:"Percolator 用多個 PSM 特徵（如 mass error, charge, length）訓練 SVM 重新排序 PSM，可在 1% FDR 下多識別 10-30% peptide。",
            exp_en:"Percolator trains an SVM on PSM features (mass error, charge, length) to re-rank PSMs — yielding 10–30% more IDs at the same FDR." },
          { type:"tf",
            stem:"是非題：MSBooster 使用深度學習預測 fragment 強度與保留時間，可進一步提升 search 靈敏度。",
            stem_en:"True/False: MSBooster uses deep learning to predict fragment intensities and retention times, further boosting search sensitivity.",
            ans:"T",
            exp:"MSBooster 整合於 FragPipe，將 deep learning 預測值作為額外特徵餵入 Percolator，可大幅提升 single-cell 或低豐度蛋白的識別率。",
            exp_en:"MSBooster integrates with FragPipe, feeding deep-learning predictions as additional features into Percolator, greatly improving sensitivity for low-input data." },
          { type:"single",
            stem:"在 1% protein FDR 報告時，下列做法何者最不正確？",
            stem_en:"Which practice is LEAST correct when reporting 1% protein FDR?",
            A:"檢查 PSM-level FDR 是否同樣 ≤ 1%", A_en:"Check that PSM-level FDR is also ≤ 1%",
            B:"檢查 peptide-level FDR", B_en:"Check peptide-level FDR",
            C:"假設 PSM 1% FDR 自動代表 protein 1% FDR", C_en:"Assume 1% PSM FDR automatically yields 1% protein FDR",
            D:"列出每個蛋白的 unique peptide 數", D_en:"Report the number of unique peptides per protein",
            ans:"C",
            exp:"protein-level FDR 因「one-hit wonder」常比 PSM FDR 嚴格得多；不能假設層級間自動傳遞。",
            exp_en:"Protein-level FDR is often stricter than PSM due to one-hit wonders; never assume FDR propagates between layers." }
        ],
        "Step 4：定量策略 (Quantification)": [
          { type:"single",
            stem:"label-free quantification (LFQ) 的核心特徵為何？",
            stem_en:"Core feature of label-free quantification (LFQ)?",
            A:"每個樣品分別上機，比較 MS1 peak area 或 spectral count", A_en:"Each sample run separately; compare MS1 peak area or spectral counts",
            B:"使用 isobaric tag 多工", B_en:"Multiplex via isobaric tags",
            C:"使用同位素標記 K/R 培養", C_en:"Use isotope-labeled K/R in culture",
            D:"在 ESI 階段加入標記", D_en:"Adds labels at ESI stage",
            ans:"A",
            exp:"LFQ 不加任何標籤，分別上機後用 MS1 強度或 spectral count 比較，MaxLFQ 是經典實作。",
            exp_en:"LFQ uses no labels — separate runs are compared by MS1 intensity or spectral counts. MaxLFQ is a classic implementation." },
          { type:"single",
            stem:"什麼是 TMT (Tandem Mass Tag) 定量？",
            stem_en:"What is TMT (Tandem Mass Tag) quantification?",
            A:"代謝標記同位素 K/R", A_en:"Metabolic isotope labeling of K/R",
            B:"胺基反應性 isobaric tag 同時標記 6-18 個樣品，MS2 reporter ion 強度比對應丰度", B_en:"Amine-reactive isobaric tags label 6–18 samples; MS2 reporter ion intensity reflects abundance",
            C:"使用抗體富集", C_en:"Antibody-based enrichment",
            D:"只能用於 PTM", D_en:"Only for PTMs",
            ans:"B",
            exp:"TMT 為 isobaric tag：化學結構相同但 MS2 中報告離子質量不同（126-135 m/z 等），TMTpro 16/18-plex 可同時處理 16/18 樣品。",
            exp_en:"TMT is an isobaric tag: same chemistry, different MS2 reporter masses (126–135 m/z). TMTpro 16/18-plex handles 16/18 samples simultaneously." },
          { type:"single",
            stem:"SILAC 最大的限制是什麼？",
            stem_en:"What is SILAC's biggest limitation?",
            A:"無法用於 PTM 分析", A_en:"Cannot be used for PTM analysis",
            B:"僅適用培養細胞，無法用於非分裂細胞或人類組織", B_en:"Only works for cultured (dividing) cells; not for non-dividing cells or human tissues",
            C:"精準度太低", C_en:"Poor precision",
            D:"成本最低", D_en:"It's the cheapest",
            ans:"B",
            exp:"SILAC 依靠細胞培養代謝吸收 ¹³C₆-Lys / ¹³C₆¹⁵N₄-Arg；無法培養的人類組織與不分裂細胞都不適用。",
            exp_en:"SILAC requires cells to metabolically incorporate ¹³C₆-Lys / ¹³C₆¹⁵N₄-Arg via culture — not feasible for human tissues or non-dividing cells." },
          { type:"single",
            stem:"什麼是 TMT 的「Ratio Compression」？",
            stem_en:"What is TMT 'ratio compression'?",
            A:"軟體壓縮存檔", A_en:"Software file compression",
            B:"MS2 中與目標母離子共流出的其他干擾胜肽進入 isolation window，污染 reporter 訊號使比值變小", B_en:"Co-eluting peptides in the isolation window contaminate reporter ions, deflating the true ratio",
            C:"試劑成本下降", C_en:"Reagent cost reduction",
            D:"SILAC 才會發生", D_en:"Only happens in SILAC",
            ans:"B",
            exp:"TMT MS2-level 量化最大限制；MS3 (SPS-MS3) 用更窄的選擇與第三級碎裂顯著校正 ratio compression。",
            exp_en:"The chief limitation of MS2-TMT; MS3 (SPS-MS3) with narrower selection and a third stage of fragmentation greatly corrects this." },
          { type:"single",
            stem:"iBAQ 最適合回答下列哪個問題？",
            stem_en:"iBAQ is best suited to answer which question?",
            A:"細胞分化過程中蛋白變化", A_en:"Protein changes during cell differentiation",
            B:"同一樣品內，蛋白質複合物中各次單元的化學計量比", B_en:"Within a single sample, the stoichiometric ratio of subunits in a complex",
            C:"不同物種間絕對蛋白量比較", C_en:"Absolute protein amount comparison across species",
            D:"PTM 位點佔有率變化", D_en:"PTM site occupancy changes",
            ans:"B",
            exp:"iBAQ = ∑MS1 強度 / 理論可偵測胜肽數，反映同一樣品內蛋白的相對「絕對」量，最適用於 stoichiometry / 複合物組成。",
            exp_en:"iBAQ = ∑MS1 intensity / theoretical detectable peptides; reflects within-sample relative absolute abundance — ideal for stoichiometry/complex composition." },
          { type:"single",
            stem:"研究 cohort 為 48 個臨床手術組織樣品，預算有限，希望最大化定量重現性。最佳策略？",
            stem_en:"48 clinical surgical samples, limited budget, max reproducibility. Best strategy?",
            A:"TMTpro 18-plex × 3 batch", A_en:"TMTpro 18-plex × 3 batches",
            B:"SILAC（培養 48 種同位素小鼠）", B_en:"SILAC (culture 48 isotope-labeled mice)",
            C:"DIA-LFQ (DIA-NN)", C_en:"DIA-LFQ (DIA-NN)",
            D:"iBAQ + 化學標記", D_en:"iBAQ + chemical labels",
            ans:"C",
            exp:"DIA-LFQ 對 cohort 規模有最佳的成本/重現性平衡，是 2024-25 臨床蛋白質體學主流。",
            exp_en:"DIA-LFQ offers the best cost/reproducibility balance at cohort scale — the 2024-25 mainstream for clinical proteomics." },
          { type:"multi",
            stem:"以下哪些屬於 label-based 定量策略？（多選）",
            stem_en:"Which of the following are label-based quantification strategies? (Multiple)",
            A:"TMT", A_en:"TMT",
            B:"SILAC", B_en:"SILAC",
            C:"iTRAQ", C_en:"iTRAQ",
            D:"LFQ", D_en:"LFQ",
            ans:["A","B","C"],
            exp:"D LFQ 是 label-free；TMT、iTRAQ 為 isobaric label，SILAC 為 metabolic label。",
            exp_en:"D LFQ is label-free; TMT/iTRAQ are isobaric, SILAC is metabolic — all three A/B/C use labels." },
          { type:"tf",
            stem:"是非題：MS3-based TMT (SPS-MS3) 的定量精準度高於 MS2-based TMT，但通量較低。",
            stem_en:"True/False: MS3-based TMT (SPS-MS3) gives higher quant accuracy than MS2-based TMT, but at lower throughput.",
            ans:"T",
            exp:"MS3 多了一層選擇與碎裂，大幅減少 ratio compression，但每個 MS3 scan 需更長時間，故通量較低。",
            exp_en:"MS3 adds an extra selection + fragmentation stage that dramatically reduces ratio compression, but each scan takes longer, lowering throughput." }
        ],
        "Step 5：品質管控 (QC)": [
          { type:"single",
            stem:"什麼是「Keratin contamination」？",
            stem_en:"What is 'keratin contamination'?",
            A:"來自皮膚屑、頭髮的角蛋白污染樣品，常因未戴手套或開放實驗台處理導致", A_en:"Keratin from skin/hair contaminating the sample — usually from no gloves or open-bench handling",
            B:"質譜儀內部金屬腐蝕", B_en:"Internal metal corrosion of the MS",
            C:"trypsin 純度不佳", C_en:"Impure trypsin",
            D:"試劑過期", D_en:"Expired reagents",
            ans:"A",
            exp:"Keratin（皮膚、頭髮、纖維蛋白）是最常見的環境污染源；理想 contaminant % < 5%。應在 clean bench 戴手套處理。",
            exp_en:"Keratins from skin/hair/fibers are the most common environmental contaminants. Ideally < 5% of total intensity. Use a clean bench with gloves." },
          { type:"single",
            stem:"PCA 圖上 PC1 完全分開兩個批次而非生物條件，最佳處理為何？",
            stem_en:"PC1 separates samples by batch rather than biology. Best action?",
            A:"忽略，繼續做 DE", A_en:"Ignore and proceed with DE",
            B:"用 ComBat 或 limma::removeBatchEffect 校正，並在 design matrix 加入 batch 變數", B_en:"Apply ComBat or limma::removeBatchEffect, and add batch as a covariate in the design matrix",
            C:"刪除一半樣品", C_en:"Delete half the samples",
            D:"重新測序所有樣品", D_en:"Re-sequence all samples",
            ans:"B",
            exp:"批次效應主導 PC1 是嚴重 confounder；標準作法是 batch correction + 在 design matrix 控制 batch 因子。",
            exp_en:"Batch effect dominating PC1 is a major confounder; correct it (ComBat / removeBatchEffect) and include batch as a covariate in the design." },
          { type:"single",
            stem:"為何 DIA 的 missing rate 通常遠低於 DDA？",
            stem_en:"Why is DIA's missing rate usually much lower than DDA?",
            A:"DIA 不需要碎裂", A_en:"DIA doesn't need fragmentation",
            B:"DIA 在預定窗內碎裂所有母離子，不存在 DDA 的「Top-N 隨機選擇」缺失", B_en:"DIA fragments all precursors within pre-defined windows — no 'Top-N stochastic selection' gaps",
            C:"DIA 自動 imputation", C_en:"DIA auto-imputes",
            D:"DIA 樣品較濃", D_en:"DIA samples are more concentrated",
            ans:"B",
            exp:"DDA 的隨機選擇是 missing 主因；DIA 全窗碎裂從採集端就解決了這個問題。",
            exp_en:"DDA's stochastic selection is the main missingness driver; DIA's wide-window fragmentation eliminates this at acquisition." },
          { type:"single",
            stem:"以下哪個是健康樣品的 CV (coefficient of variation) 期望值？",
            stem_en:"Which is the expected CV (coefficient of variation) for a healthy sample?",
            A:"LFQ ≤ 50%、TMT ≤ 40%", A_en:"LFQ ≤ 50%, TMT ≤ 40%",
            B:"LFQ ≤ 20%、TMT ≤ 10%（DIA-Astral 可達 ≤ 5%）", B_en:"LFQ ≤ 20%, TMT ≤ 10% (DIA-Astral can reach ≤ 5%)",
            C:"LFQ ≤ 80%、TMT ≤ 70%", C_en:"LFQ ≤ 80%, TMT ≤ 70%",
            D:"CV 越高越好", D_en:"Higher CV is better",
            ans:"B",
            exp:"健康 CV：LFQ ≤ 20%、TMT ≤ 10%。Astral DIA 可達 ≤ 5%。CV 高代表技術變異大或樣品異質。",
            exp_en:"Healthy CV: LFQ ≤ 20%, TMT ≤ 10%. Astral DIA can reach ≤ 5%. High CV signals technical noise or sample heterogeneity." },
          { type:"multi",
            stem:"以下哪些是樣品層級 QC 的核心指標？（多選）",
            stem_en:"Which are core sample-level QC metrics? (Multiple)",
            A:"# Proteins / # Peptides 識別數", A_en:"# Proteins / # Peptides identified",
            B:"CV (replicate variability)", B_en:"CV (replicate variability)",
            C:"Missing rate", C_en:"Missing rate",
            D:"Contaminant fraction", D_en:"Contaminant fraction",
            ans:["A","B","C","D"],
            exp:"四者皆為樣品層級 QC 的關鍵指標。",
            exp_en:"All four are key sample-level QC metrics." },
          { type:"tf",
            stem:"是非題：在 QC 階段就應移除 Contaminants 與 Reverse hits，否則會污染下游 DE 分析。",
            stem_en:"True/False: Contaminants and reverse hits should be removed at the QC stage; otherwise they corrupt downstream DE.",
            ans:"T",
            exp:"未過濾的 contaminants 與 reverse hits 會影響 normalization、distribution、DE 統計，是 QC 最重要的清理步驟之一。",
            exp_en:"Unfiltered contaminants and reverse hits affect normalization, distributions, and DE statistics — a critical QC cleanup step." },
          { type:"single",
            stem:"為何業界常用 HeLa Digest 標準樣品做日常 QC？",
            stem_en:"Why is HeLa Digest commonly used for daily QC?",
            A:"HeLa 細胞是癌症細胞，特別有趣", A_en:"HeLa cells are cancerous and interesting",
            B:"穩定可重現、組成複雜，長期追蹤 # protein / # peptide / RT 等指標可早期發現儀器衰退", B_en:"Stable, reproducible, complex — long-term tracking of # proteins / # peptides / RT detects instrument degradation early",
            C:"HeLa 不需消化", C_en:"HeLa doesn't need digestion",
            D:"HeLa 是合成樣品", D_en:"HeLa is synthetic",
            ans:"B",
            exp:"HeLa digest（如 Pierce HeLa Digest）批間極穩定，是 community 公認的儀器 longitudinal benchmark。",
            exp_en:"Pierce HeLa Digest is extremely stable batch-to-batch — the community standard for longitudinal instrument benchmarking." },
          { type:"single",
            stem:"什麼是 missed cleavage rate 的健康範圍？",
            stem_en:"What is the healthy range for missed cleavage rate?",
            A:"&lt; 25%（理想 &lt; 15%）", A_en:"< 25% (ideally < 15%)",
            B:"&lt; 80%", B_en:"< 80%",
            C:"&lt; 95%", C_en:"< 95%",
            D:"沒有上限要求", D_en:"No upper limit",
            ans:"A",
            exp:"理想消化完全度 &lt; 25% missed cleavage；過高代表酵素活性、時間或樣品問題。",
            exp_en:"Ideal: < 25% missed cleavage; higher rates signal enzyme/time/sample issues." }
        ],
        "Step 6：標準化 (Normalization)": [
          { type:"single",
            stem:"為什麼蛋白質體學必須做 normalization？",
            stem_en:"Why is normalization mandatory in proteomics?",
            A:"純粹為了美化圖表", A_en:"Just to make plots prettier",
            B:"同一份樣品分兩個小份上機都可能差異 30-50%（注射量、LC 狀態、ESI 穩定性）；不校正則無法比較", B_en:"Even two technical replicates of the same sample can differ 30–50% (injection, LC, ESI); without normalization, comparison is impossible",
            C:"normalization 增加蛋白覆蓋", C_en:"Normalization adds protein coverage",
            D:"無需 normalization", D_en:"Not needed",
            ans:"B",
            exp:"技術變異無所不在，normalization 是讓樣品之間「真正可比」的前提。",
            exp_en:"Technical variation is ubiquitous; normalization is the prerequisite for samples to be truly comparable." },
          { type:"single",
            stem:"VSN (Variance Stabilizing Normalization) 的最大優勢為何？",
            stem_en:"What is VSN's biggest advantage?",
            A:"速度最快", A_en:"Fastest",
            B:"同時 log-like 轉換與標準化，使所有強度級別的 variance 近似一致", B_en:"Combines log-like transformation with normalization to stabilize variance across all intensity levels",
            C:"完全不需要 reference", C_en:"Needs no reference",
            D:"不能處理蛋白資料", D_en:"Doesn't work for proteins",
            ans:"B",
            exp:"VSN 同時轉換與標準化，讓低豐度與高豐度蛋白的 variance 估計都更合理，2018 benchmark 中排名最佳。",
            exp_en:"VSN simultaneously transforms and normalizes, giving fair variance estimates across all intensity ranges — top-ranked in the 2018 benchmark." },
          { type:"single",
            stem:"關於 Quantile normalization 的潛在風險，下列何者最正確？",
            stem_en:"Which is the most accurate concern about Quantile normalization?",
            A:"無風險，永遠最佳", A_en:"No risk; always best",
            B:"強制 distribution 完全一致，若樣品間真有全域生物學差異（如疾病整體上調）會被「強行抹平」", B_en:"Forces identical distributions; real global biological shifts (e.g., disease-wide upregulation) get erased",
            C:"計算太慢", C_en:"Too slow",
            D:"只能用於 microarray", D_en:"Only works for microarrays",
            ans:"B",
            exp:"Quantile 是最強烈的 normalization，對 technical-only 差異有效，但若樣品間真有生物差異會抹除訊號。",
            exp_en:"Quantile is the most aggressive method; great for technical-only variation, but it erases real biological differences." },
          { type:"single",
            stem:"TMT 多 batch 整合最推薦的標準化方法為何？",
            stem_en:"For multi-batch TMT integration, what's the recommended method?",
            A:"Cyclic LOESS", A_en:"Cyclic LOESS",
            B:"IRS (Internal Reference Scaling) — 每 batch 含 pooled reference channel 對齊", B_en:"IRS (Internal Reference Scaling) — pool reference channel aligns each batch",
            C:"不做任何 normalization", C_en:"No normalization",
            D:"Z-score", D_en:"Z-score",
            ans:"B",
            exp:"IRS 是 TMT 跨批次整合黃金標準；reference channel 提供統一錨點，再搭配 median normalization。",
            exp_en:"IRS is the gold standard for cross-batch TMT; the reference channel provides a common anchor, often combined with median normalization." },
          { type:"single",
            stem:"Normalization 的核心假設為何？",
            stem_en:"The core assumption of normalization?",
            A:"大多數蛋白質的真實表達在條件之間是不變的（中位數穩定性假設）", A_en:"Most proteins' true expression is unchanged across conditions (median-stability assumption)",
            B:"所有蛋白的表達都是動態變化", B_en:"All proteins change dynamically",
            C:"normalization 與數據無關", C_en:"Normalization is independent of data",
            D:"normalization 自動辨識生物差異", D_en:"Normalization auto-detects biological differences",
            ans:"A",
            exp:"中位數穩定性假設是大多數標準化方法的基石；當此假設不成立時（如全域生物變化），需用 Normics 等更穩健方法。",
            exp_en:"The median-stability assumption underpins most normalization methods. When violated (global biology shift), use robust variants like Normics." },
          { type:"multi",
            stem:"以下哪些是常見的 normalization 方法？（多選）",
            stem_en:"Which are common normalization methods? (Multiple)",
            A:"Median centering", A_en:"Median centering",
            B:"VSN", B_en:"VSN",
            C:"Cyclic LOESS", C_en:"Cyclic LOESS",
            D:"Quantile", D_en:"Quantile",
            ans:["A","B","C","D"],
            exp:"四者都是常用方法，各有適用情境。",
            exp_en:"All four are common methods, each with its niche." },
          { type:"tf",
            stem:"是非題：在標準化之前必須先過濾 contaminants 與 reverse hits，否則會影響 normalization 的中位數估計。",
            stem_en:"True/False: Contaminants and reverse hits must be filtered before normalization; otherwise they bias the median estimate.",
            ans:"T",
            exp:"未過濾的污染物會影響整體 distribution 與 median 估計，是 normalization 前必要的清理步驟。",
            exp_en:"Unfiltered contaminants distort distributions and median estimates — essential to remove before normalization." },
          { type:"single",
            stem:"以下何者最不適合 normalization？",
            stem_en:"Which is the LEAST suitable scenario for the listed normalization?",
            A:"LFQ 單批次：median 或 VSN", A_en:"Single-batch LFQ: median or VSN",
            B:"TMT 多批次：IRS + median", B_en:"Multi-batch TMT: IRS + median",
            C:"疾病組整體上調 + 健康組：直接 Quantile", C_en:"Disease vs healthy with global upregulation: direct Quantile",
            D:"DIA single-batch：VSN", D_en:"Single-batch DIA: VSN",
            ans:"C",
            exp:"全域生物差異情境下 Quantile 會抹除訊號，應改用 Normics 或 robust median 變體。",
            exp_en:"With global biological shifts, Quantile erases signal; use Normics or a robust median variant instead." }
        ],
        "Step 7：缺失值處理 (Imputation)": [
          { type:"single",
            stem:"一個蛋白在 Control 4/4 都偵測到，但在 Disease 0/4 偵測到。最合適的處理為何？",
            stem_en:"A protein is detected 4/4 in Control but 0/4 in Disease. Best approach?",
            A:"KNN 把 Disease 補成 Control 群體平均", A_en:"KNN to fill Disease with Control mean",
            B:"視為 MNAR，用 QRILC / MinProb 從左尾抽樣補", B_en:"Treat as MNAR; left-tail sampling (QRILC / MinProb)",
            C:"直接刪除該蛋白", C_en:"Drop this protein",
            D:"補 0", D_en:"Replace with 0",
            ans:"B",
            exp:"這是 MNAR 典型模式（疾病組真實低豐度）；應從左尾抽樣以保留「低訊號」生物學意義。KNN 會錯誤拉到中等值。",
            exp_en:"Classic MNAR (truly low in disease); left-tail sampling preserves the 'low signal' biology. KNN would wrongly pull it to mid-range." },
          { type:"single",
            stem:"為何 KNN 不適合用於 MNAR 缺失？",
            stem_en:"Why is KNN inappropriate for MNAR?",
            A:"KNN 太慢", A_en:"Too slow",
            B:"KNN 會將「真實低表達」蛋白拉到鄰居平均值，掩蓋真實低訊號", B_en:"KNN pulls truly low-expressed proteins toward neighbor averages, masking the real low signal",
            C:"KNN 對 outlier 不敏感", C_en:"KNN is insensitive to outliers",
            D:"KNN 不能處理連續變數", D_en:"KNN can't handle continuous variables",
            ans:"B",
            exp:"KNN 假設 missing 是隨機的（MAR），用鄰居推測；對 MNAR 此假設不成立，會錯誤抬高真實低訊號。",
            exp_en:"KNN assumes MAR (random); for MNAR this assumption fails, and the imputer wrongly inflates real low signals." },
          { type:"single",
            stem:"什麼是 MNAR 與 MAR 的本質區別？",
            stem_en:"Fundamental difference between MNAR and MAR?",
            A:"MNAR：低於偵測極限的真實低豐度；MAR：偶然性技術缺失（如 DDA 隨機）", A_en:"MNAR: truly low (below LOD); MAR: stochastic technical loss (e.g., DDA randomness)",
            B:"兩者完全相同", B_en:"They are identical",
            C:"MAR 才是真正的缺失", C_en:"Only MAR is real missingness",
            D:"MNAR 只發生在 RNA-seq", D_en:"MNAR only occurs in RNA-seq",
            ans:"A",
            exp:"MNAR = 「真的很低」，需 left-censored 方法；MAR = 「測得到但漏看」，需 KNN/RF 等鄰居推測。",
            exp_en:"MNAR = 'truly low', needs left-censored methods; MAR = 'detectable but missed', needs KNN/RF neighbor-based methods." },
          { type:"single",
            stem:"2024 benchmark 中綜合表現最佳的 imputation 策略為何？",
            stem_en:"The top-performing imputation strategy in 2024 benchmarks?",
            A:"全部補 0", A_en:"Replace all with 0",
            B:"Mixed imputation（每蛋白判斷 MNAR/MAR 後分別用 QRILC 或 RF）", B_en:"Mixed imputation (per-protein MNAR/MAR diagnosis, then QRILC or RF)",
            C:"全部補平均值", C_en:"Replace with mean",
            D:"完全不處理", D_en:"No imputation",
            ans:"B",
            exp:"Mixed imputation 結合兩種機制的優勢；DEP 套件的標準推薦做法。",
            exp_en:"Mixed imputation combines the strengths of both — the DEP package's standard recommendation." },
          { type:"multi",
            stem:"以下哪些是 MNAR 適用的 imputation 方法？（多選）",
            stem_en:"Which imputers are suitable for MNAR? (Multiple)",
            A:"QRILC", A_en:"QRILC",
            B:"MinDet / MinProb", B_en:"MinDet / MinProb",
            C:"KNN", C_en:"KNN",
            D:"從觀測值的 1% 分位 + 微小變異抽樣", D_en:"Sample from 1st percentile + small noise of observed",
            ans:["A","B","D"],
            exp:"A、B、D 都是左截尾方法，適合 MNAR；KNN 是 MAR 適用。",
            exp_en:"A, B, D are left-censored methods for MNAR; KNN is for MAR." },
          { type:"single",
            stem:"MSstats 套件如何處理缺失值？",
            stem_en:"How does MSstats handle missing values?",
            A:"完全忽略", A_en:"Ignores them entirely",
            B:"內建 mixed model 將 missingness 與 DE 同時建模，不需另做 post-hoc imputation", B_en:"Built-in mixed model jointly models missingness and DE; no separate post-hoc imputation needed",
            C:"用 t-test 補值", C_en:"Uses t-tests to impute",
            D:"刪除有缺失的所有蛋白", D_en:"Drops all proteins with any missing",
            ans:"B",
            exp:"MSstats `MBimpute=TRUE` 將 missing 整合進其 linear mixed model；再做 post-hoc imputation 反而 double-impute。",
            exp_en:"MSstats `MBimpute=TRUE` folds missingness into its linear mixed model; adding post-hoc imputation causes double-imputation." },
          { type:"tf",
            stem:"是非題：「補 0」是處理缺失值的最佳做法。",
            stem_en:"True/False: Replacing missing with 0 is the best practice.",
            ans:"F",
            exp:"補 0 引入嚴重偏差（極端值），扭曲 fold change 與 variance 估計，是最差的策略之一。應該用 MNAR/MAR 適配方法。",
            exp_en:"Zero-imputation introduces severe bias (extreme values), distorting fold changes and variance — one of the worst strategies. Use MNAR/MAR-appropriate methods." },
          { type:"single",
            stem:"DIA 的 missing rate 通常較 DDA 低，那是否就完全不需要 imputation？",
            stem_en:"DIA missing rates are usually lower than DDA — does that mean no imputation needed at all?",
            A:"是的，DIA 無缺失", A_en:"Yes, DIA has no missing values",
            B:"仍會有少量 MNAR 缺失（低豐度未達 LOD），應根據比例與分析需要決定", B_en:"Still has some MNAR missing (low-abundance below LOD); decide based on rate and analysis needs",
            C:"DIA 自動補值", C_en:"DIA auto-imputes",
            D:"無關 imputation", D_en:"Unrelated to imputation",
            ans:"B",
            exp:"DIA 即便缺失率 < 5%，剩餘 missing 多為真實 MNAR；MSstats / DEP 仍會做適當處理。",
            exp_en:"Even at < 5% missing, DIA's residual gaps are usually true MNAR; MSstats/DEP still handle them appropriately." }
        ],
        "Step 8：差異表達分析 (DE)": [
          { type:"single",
            stem:"為什麼蛋白質體學的 small-n（3-6 per group）不適合用一般 t-test？",
            stem_en:"Why is plain t-test poor for small-n (3–6 per group) proteomics?",
            A:"t-test 不能處理連續變數", A_en:"t-test can't handle continuous variables",
            B:"小樣本下 variance 估計極不穩定；moderated t (limma) 借用其他蛋白資訊提升統計力", B_en:"Small-sample variance estimates are unstable; moderated t (limma) borrows information from other proteins",
            C:"t-test 只能比較 RNA", C_en:"t-test only works for RNA",
            D:"t-test 太慢", D_en:"t-test is too slow",
            ans:"B",
            exp:"n=3 時 variance 估計易出現極小值（假高 t），limma 的 empirical Bayes 收縮顯著解決此問題。",
            exp_en:"At n=3, variance estimates may dip very low (inflating t); limma's empirical Bayes shrinkage solves this." },
          { type:"single",
            stem:"一個蛋白 log2FC = 0.15、adj.p = 0.001。最合理的解讀為何？",
            stem_en:"log2FC = 0.15 and adj.p = 0.001 — best interpretation?",
            A:"強訊號，列為主要 hit", A_en:"Strong signal — top hit",
            B:"統計不顯著，移除", B_en:"Not significant, remove",
            C:"統計顯著但 effect size 太小（~11% 變化），需結合生物學上下文判斷", C_en:"Significant but tiny effect size (~11% change); needs biological context",
            D:"假陽性", D_en:"False positive",
            ans:"C",
            exp:"統計顯著 ≠ 生物學重要。0.15 log2FC 約 11% 變化，應根據生物學意義評估是否真的有 functional impact。",
            exp_en:"Statistical significance ≠ biological importance. 0.15 log2FC = ~11% change; check whether the change has functional impact." },
          { type:"single",
            stem:"以下哪個是 limma 套件的核心統計概念？",
            stem_en:"limma's core statistical concept?",
            A:"empirical Bayes 變異收縮（borrow strength across genes/proteins）", A_en:"Empirical Bayes variance shrinkage (borrow strength across genes/proteins)",
            B:"deep learning 預測 fold change", B_en:"Deep-learning fold-change prediction",
            C:"純粹用 t-test", C_en:"Plain t-test",
            D:"K-means 聚類", D_en:"K-means clustering",
            ans:"A",
            exp:"limma 借用所有 protein 的 variance 資訊將個別蛋白的 variance 收縮到群體中位數，產生 moderated t，是 small-n 統計的關鍵。",
            exp_en:"limma shrinks each protein's variance toward the population median by borrowing from all others, producing moderated t — key for small-n stats." },
          { type:"single",
            stem:"在 design matrix 中加入 batch 作為 covariate 的目的為何？",
            stem_en:"Why add batch as a covariate in the design matrix?",
            A:"純粹形式好看", A_en:"Just looks nicer",
            B:"統計上「校正」batch 效應，使主要興趣的條件比較不受 batch 干擾", B_en:"Statistically 'controls' for batch so the comparison of interest is not confounded",
            C:"加速計算", C_en:"Speed up computation",
            D:"增加識別蛋白數", D_en:"Increase protein IDs",
            ans:"B",
            exp:"design matrix 中含 batch（如 ~ group + batch）讓 limma/MSstats 同時校正 batch 與比較條件，比後處理校正更穩健。",
            exp_en:"Including batch in the design (~ group + batch) lets limma/MSstats correct for batch simultaneously with the comparison — more robust than post-hoc correction." },
          { type:"single",
            stem:"以下何者是 MSstats 相對 limma 的優勢？",
            stem_en:"MSstats's advantage over limma?",
            A:"MSstats 完全不需要程式設計", A_en:"MSstats needs no programming at all",
            B:"專為 proteomics 設計的 peptide-level linear mixed model；內建 missing-value 處理", B_en:"Designed for proteomics with peptide-level linear mixed model; built-in missing-value handling",
            C:"MSstats 速度比較快", C_en:"MSstats is faster",
            D:"完全沒有優勢", D_en:"No advantage",
            ans:"B",
            exp:"MSstats 在 peptide 與 protein 兩層建立 mixed model，並把 missingness 整合進去；新手友善且專為 proteomics 設計。",
            exp_en:"MSstats fits mixed models at both peptide and protein levels, with missingness integrated — proteomics-specific and beginner-friendly." },
          { type:"multi",
            stem:"以下哪些行為是 DE 分析應避免的錯誤？（多選）",
            stem_en:"Which behaviors are DE analysis mistakes to avoid? (Multiple)",
            A:"用未校正的 p-value 篩選顯著蛋白", A_en:"Filter by uncorrected p-values",
            B:"n=3 卻直接用 raw t-test", B_en:"Use raw t-test with n=3",
            C:"在多 batch 資料未做 batch 校正", C_en:"Ignore batch correction in multi-batch data",
            D:"使用 limma 並做 BH 校正", D_en:"Use limma with BH correction",
            ans:["A","B","C"],
            exp:"D 是正確做法；其他三項都是常見錯誤。",
            exp_en:"D is correct practice; the other three are common mistakes." },
          { type:"tf",
            stem:"是非題：在報告差異表達結果時應同時提供 log2FC 與 adj.p (BH-corrected) 兩個指標，並設定合理閾值。",
            stem_en:"True/False: DE results should report log2FC and adj.p (BH-corrected) together with sensible thresholds.",
            ans:"T",
            exp:"單看 p-value 易誤判 effect size 不重要的訊號；單看 fold change 易誤判統計不穩定的雜訊。",
            exp_en:"p-value alone misses tiny effect sizes; fold change alone catches unstable noise. Always report both with thresholds." },
          { type:"single",
            stem:"使用 limma 做 DE 後最後一步通常是？",
            stem_en:"Last typical step after limma DE?",
            A:"BH (Benjamini-Hochberg) 校正多重比較問題，得到 adj.p", A_en:"BH (Benjamini-Hochberg) correction for multiple testing → adj.p",
            B:"重新做 t-test", B_en:"Redo t-tests",
            C:"刪除所有 p > 0.05 的蛋白", C_en:"Drop all proteins with p > 0.05",
            D:"重做 search", D_en:"Re-run search",
            ans:"A",
            exp:"3000 個蛋白同時測試的話，未校正下會有 ~150 個假陽性；BH 校正是 proteomics DE 的標準做法。",
            exp_en:"Testing 3000 proteins yields ~150 false positives uncorrected; BH correction is standard for proteomics DE." }
        ],
        "Step 9：功能富集分析 (Enrichment)": [
          { type:"single",
            stem:"ORA 與 GSEA 最關鍵的本質差異為何？",
            stem_en:"Most fundamental difference between ORA and GSEA?",
            A:"ORA 更快", A_en:"ORA is faster",
            B:"ORA 用 binary（顯著/不顯著）hit list；GSEA 用整體排序 ranked list，捕捉協調性趨勢", B_en:"ORA uses a binary hit list; GSEA uses a full ranked list to catch coordinated trends",
            C:"GSEA 只支援 KEGG", C_en:"GSEA only supports KEGG",
            D:"兩者完全相同", D_en:"They are identical",
            ans:"B",
            exp:"ORA 需要 cutoff（hit list），GSEA 用整體排序不需 cutoff。兩者互補，常並用。",
            exp_en:"ORA needs a cutoff (hit list); GSEA uses the full ranked list with no cutoff. They are complementary." },
          { type:"single",
            stem:"做 ORA 時用 UniProt 全部 20000 個蛋白作 background，會有什麼問題？",
            stem_en:"Using all 20000 UniProt proteins as ORA background — what's the issue?",
            A:"沒問題，這是標準作法", A_en:"None — this is standard",
            B:"實驗只測到 5000 蛋白，背景過大會大幅膨脹 enrichment 顯著性（假陽性）", B_en:"Experiment detects only 5000; using 20000 as background inflates significance (false positives)",
            C:"計算太慢", C_en:"Too slow",
            D:"UniProt 數據不正確", D_en:"UniProt is wrong",
            ans:"B",
            exp:"必須用「實驗中所有偵測到的蛋白」作 background，否則 p-value 被大幅低估，這是 enrichment 最常見錯誤。",
            exp_en:"Background must be 'all proteins detected in the experiment'; otherwise p-values are heavily underestimated — the #1 enrichment mistake." },
          { type:"single",
            stem:"想視覺化「上調蛋白間的協同網絡」並找 hub，最佳工具為何？",
            stem_en:"To visualize 'synergistic networks of upregulated proteins' and find hubs?",
            A:"STRING + Cytoscape（PPI 網絡 + functional clustering）", A_en:"STRING + Cytoscape (PPI + functional clustering)",
            B:"GSEA 火山圖", B_en:"GSEA volcano",
            C:"Excel barplot", C_en:"Excel barplot",
            D:"不需要視覺化", D_en:"No visualization needed",
            ans:"A",
            exp:"STRING 提供 PPI 證據網絡，Cytoscape 配合 EnrichmentMap 為 Nature Protocols 推薦的標準做法。",
            exp_en:"STRING provides PPI evidence; Cytoscape + EnrichmentMap is the Nature Protocols-recommended pipeline." },
          { type:"single",
            stem:"clusterProfiler 套件做 ORA 時，最容易被忽略的關鍵參數為何？",
            stem_en:"In clusterProfiler ORA, the most commonly overlooked critical parameter?",
            A:"P-value 閾值", A_en:"P-value cutoff",
            B:"universe（background gene/protein 集合）", B_en:"universe (background gene/protein set)",
            C:"出圖顏色", C_en:"Plot colors",
            D:"作者引用", D_en:"Author citation",
            ans:"B",
            exp:"預設 universe 是「資料庫中所有 annotated 蛋白」，需手動傳入實驗偵測蛋白；否則大幅膨脹顯著性。",
            exp_en:"The default universe is 'all annotated proteins in the database'; manually pass detected proteins, else significance is inflated." },
          { type:"single",
            stem:"GSEA 的核心統計量為何？",
            stem_en:"GSEA's core statistic?",
            A:"Fisher's exact test", A_en:"Fisher's exact test",
            B:"Kolmogorov-Smirnov 變體 + permutation 顯著性", B_en:"Kolmogorov-Smirnov variant + permutation significance",
            C:"純粹 χ²", C_en:"Plain chi-square",
            D:"Bayesian inference", D_en:"Bayesian inference",
            ans:"B",
            exp:"GSEA 計算 enrichment score（基於排序中 ranked enrichment 軌跡），用 permutation 評估顯著性。",
            exp_en:"GSEA computes enrichment scores (running enrichment trajectory along the ranked list) and evaluates significance via permutation." },
          { type:"multi",
            stem:"以下哪些是常用的 functional 資料庫？（多選）",
            stem_en:"Which are common functional databases? (Multiple)",
            A:"GO (Gene Ontology)", A_en:"GO (Gene Ontology)",
            B:"KEGG Pathway", B_en:"KEGG Pathway",
            C:"Reactome", C_en:"Reactome",
            D:"MSigDB Hallmark", D_en:"MSigDB Hallmark",
            ans:["A","B","C","D"],
            exp:"四者皆為常用 functional 資料庫；各有特色（GO 廣泛 / KEGG 視覺化 / Reactome 免費 / MSigDB Hallmark 最精煉）。",
            exp_en:"All four are common; GO is broad, KEGG has clean diagrams, Reactome is free, MSigDB Hallmark is distilled." },
          { type:"tf",
            stem:"是非題：g:Profiler、Enrichr、clusterProfiler 都是常用的 ORA 工具。",
            stem_en:"True/False: g:Profiler, Enrichr, and clusterProfiler are all common ORA tools.",
            ans:"T",
            exp:"三者皆為主流 ORA 工具；g:Profiler 與 Enrichr 為 web-based，clusterProfiler 為 R 套件。",
            exp_en:"All three are mainstream ORA tools; g:Profiler and Enrichr are web-based, clusterProfiler is an R package." },
          { type:"single",
            stem:"做 GSEA 時用什麼數值排序蛋白？",
            stem_en:"What metric is typically used to rank proteins for GSEA?",
            A:"純 p-value", A_en:"P-value alone",
            B:"signed -log10(p) 或 log2FC × -log10(p)，包含方向資訊", B_en:"signed -log10(p) or log2FC × -log10(p), with direction info",
            C:"純粹 fold change，不帶方向", C_en:"Plain fold change without direction",
            D:"細胞數", D_en:"Cell counts",
            ans:"B",
            exp:"GSEA 需 signed ranking（含上/下調方向），常用 signed -log10(p) 或 log2FC × -log10(p) 整合 effect size 與顯著性。",
            exp_en:"GSEA needs a signed ranking (up/down direction); signed -log10(p) or log2FC × -log10(p) integrates effect size and significance." }
        ]
      },
      "進階分析主題": {
        "Advanced：PTM 修飾分析": [
          { type:"single",
            stem:"磷酸化修飾在 MS 中的質量變化為何？",
            stem_en:"What mass shift does phosphorylation add in MS?",
            A:"+42 Da", A_en:"+42 Da",
            B:"+80 Da（HPO3）", B_en:"+80 Da (HPO3)",
            C:"+114 Da", C_en:"+114 Da",
            D:"+57 Da", D_en:"+57 Da",
            ans:"B",
            exp:"磷酸基團 HPO3 質量 +79.97 Da，常標示 +80 Da。發生於 S/T/Y。",
            exp_en:"The HPO3 group adds +79.97 Da (commonly labeled +80) on S/T/Y residues." },
          { type:"single",
            stem:"為何 phospho-peptide 必須先 enrichment 才能 MS 偵測？",
            stem_en:"Why must phospho-peptides be enriched before MS detection?",
            A:"偵測太慢", A_en:"Too slow to detect",
            B:"磷酸胜肽豐度通常比 unmodified 低 1000-10000 倍，未富集會被淹沒", B_en:"Phospho-peptides are typically 1000–10000× less abundant than unmodified — overwhelmed without enrichment",
            C:"磷酸破壞質譜儀", C_en:"Phosphate damages the MS",
            D:"沒有必要 enrichment", D_en:"Enrichment unnecessary",
            ans:"B",
            exp:"低豐度 PTM 在複雜胜肽混合物中需專屬富集（TiO₂、Fe-IMAC）才能達到偵測極限。",
            exp_en:"Low-abundance PTMs require dedicated enrichment (TiO₂, Fe-IMAC) to reach detection limits in complex mixtures." },
          { type:"single",
            stem:"以下哪個是 phospho-peptide 富集的主流策略？",
            stem_en:"Which is mainstream for phospho-peptide enrichment?",
            A:"Anti-cap antibody（5' cap）", A_en:"Anti-cap antibody (5' cap)",
            B:"TiO₂ MOAC 或 Fe³⁺/Ti⁴⁺-IMAC（金屬親合層析）", B_en:"TiO₂ MOAC or Fe³⁺/Ti⁴⁺-IMAC (metal affinity chromatography)",
            C:"純粹 LC 分離", C_en:"Plain LC",
            D:"PCR", D_en:"PCR",
            ans:"B",
            exp:"金屬親合（TiO₂、Fe-IMAC）利用磷酸基團與金屬的螯合作用富集，是目前主流。",
            exp_en:"Metal affinity (TiO₂, Fe-IMAC) exploits phosphate-metal chelation — the current mainstream." },
          { type:"single",
            stem:"PTM site localization probability = 0.5 代表什麼？",
            stem_en:"PTM localization probability = 0.5 means?",
            A:"高信心位點", A_en:"High-confidence site",
            B:"不存在 PTM", B_en:"No PTM present",
            C:"位點不確定（兩個可能位置難以區分），不應作為 Class I 報告", C_en:"Site is ambiguous (two candidates indistinguishable); not Class I-reportable",
            D:"軟體錯誤", D_en:"Software bug",
            ans:"C",
            exp:"Class I site 需 probability ≥ 0.75 且 delta score &gt; 8；0.5 代表兩位點機率相等，無法確定。",
            exp_en:"Class I sites need probability ≥ 0.75 and delta score > 8; 0.5 means equal probability between two — undetermined." },
          { type:"single",
            stem:"為什麼分析 ubiquitination 後常難以區分 Ub 與 NEDD8？",
            stem_en:"Why is Ub hard to distinguish from NEDD8 after trypsin digestion?",
            A:"Trypsin 切後兩者都留下相同 GG remnant，質量無差異", A_en:"Trypsin leaves identical GG remnants for both — no mass difference",
            B:"NEDD8 不存在於人類", B_en:"NEDD8 doesn't exist in humans",
            C:"兩者會互相反應", C_en:"They react with each other",
            D:"抗體不可靠", D_en:"Antibodies are unreliable",
            ans:"A",
            exp:"K-εGG 富集得到的 modification 嚴格上是「Ub-like」，因 Trypsin 切後 Ub/NEDD8/ISG15 都留 GG。",
            exp_en:"K-εGG enrichment yields 'Ub-like' marks; Ub/NEDD8/ISG15 all leave GG after trypsin." },
          { type:"multi",
            stem:"以下哪些是常見的 PTM 分析工具/功能？（多選）",
            stem_en:"Which are common PTM tools/functions? (Multiple)",
            A:"MaxQuant Phospho(STY) workflow", A_en:"MaxQuant Phospho(STY) workflow",
            B:"FragPipe PTM-Prophet（位點 localization）", B_en:"FragPipe PTM-Prophet (site localization)",
            C:"Ascore (Beausoleil 2006) 評分", C_en:"Ascore (Beausoleil 2006) scoring",
            D:"BWA aligner（短讀對齊）", D_en:"BWA aligner (short-read alignment)",
            ans:["A","B","C"],
            exp:"D 是 DNA-seq 工具，與 PTM 無關。",
            exp_en:"D is a DNA-seq tool, unrelated to PTM." },
          { type:"tf",
            stem:"是非題：2024 benchmark 顯示「Fe-NTA → TiO₂ → Fe-NTA 三步驟序列富集」可比單次富集多 20% phospho-peptide。",
            stem_en:"True/False: 2024 benchmarks show that 'Fe-NTA → TiO₂ → Fe-NTA' tandem enrichment yields ~20% more phospho-peptides than single-step.",
            ans:"T",
            exp:"不同富集方法捕獲不同 subset 的 phospho-peptide；序列性富集可大幅提升覆蓋率。",
            exp_en:"Different enrichment methods capture different phospho-peptide subsets; sequential enrichment substantially expands coverage." },
          { type:"single",
            stem:"在 phospho-proteomics 中，HCD vs ETD 碎裂方式的權衡為何？",
            stem_en:"HCD vs ETD trade-off in phospho-proteomics?",
            A:"HCD 較快、廣泛使用；ETD 較慢但保留 labile 磷酸基團，特別有利於 site localization", A_en:"HCD is faster and widely used; ETD is slower but preserves labile phosphates — better for site localization",
            B:"兩者無差別", B_en:"No difference",
            C:"ETD 完全取代 HCD", C_en:"ETD fully replaces HCD",
            D:"HCD 不能用於 PTM", D_en:"HCD doesn't work for PTM",
            ans:"A",
            exp:"HCD 是 routine 的選擇；ETD/EThcD 在 PTM 位點定位上有顯著優勢，常作補充。",
            exp_en:"HCD is the routine choice; ETD/EThcD significantly improves PTM site localization, often used as a complement." }
        ],
        "Advanced：靶向蛋白質體學 (Targeted)": [
          { type:"single",
            stem:"從 DIA discovery 找到 12 個 candidate biomarker，要在 200 個臨床樣本驗證。最佳方法為何？",
            stem_en:"12 biomarker candidates from DIA discovery, validate on 200 clinical samples. Best method?",
            A:"重做 DIA 200 次", A_en:"Repeat DIA 200 times",
            B:"PRM 或 SureQuant + SIS 內標", B_en:"PRM or SureQuant + SIS internal standards",
            C:"Western Blot", C_en:"Western blot",
            D:"完整 top-down", D_en:"Full top-down",
            ans:"B",
            exp:"PRM / SureQuant 結合 SIS（synthetic isotope-labeled peptide）可提供高精準、可重現、絕對定量，是 validation 階段的金標準。",
            exp_en:"PRM / SureQuant with SIS provides precise, reproducible, absolute quantitation — the gold standard for validation." },
          { type:"single",
            stem:"PRM (Parallel Reaction Monitoring) 相對 SRM/MRM 的優勢為何？",
            stem_en:"PRM's advantage over SRM/MRM?",
            A:"PRM 速度更快", A_en:"PRM is faster",
            B:"高解析度 Orbitrap + 同時掃描所有 fragment ions，干擾大幅減少，且 transition 可後處理選擇", B_en:"High-res Orbitrap + scans all fragments simultaneously — much less interference, transitions chosen post-hoc",
            C:"PRM 通量更高", C_en:"PRM has higher throughput",
            D:"PRM 不需要 internal standard", D_en:"PRM needs no internal standards",
            ans:"B",
            exp:"PRM 用 Orbitrap 高解析度同時記錄所有 fragment ions，可後選擇 transition；干擾大減。",
            exp_en:"PRM uses high-res Orbitrap to record all fragments simultaneously, choosing transitions post-hoc; greatly reducing interference." },
          { type:"single",
            stem:"SRM/MRM 通常在什麼質譜儀上執行？",
            stem_en:"SRM/MRM is typically performed on what kind of MS?",
            A:"Triple Quadrupole (QqQ)", A_en:"Triple Quadrupole (QqQ)",
            B:"FT-ICR", B_en:"FT-ICR",
            C:"MALDI-TOF", C_en:"MALDI-TOF",
            D:"GC-MS", D_en:"GC-MS",
            ans:"A",
            exp:"Triple quadrupole 是 SRM/MRM 標準平台：Q1 選母離子 → Q2 碎裂 → Q3 選特定 fragment。",
            exp_en:"Triple quadrupoles are the SRM/MRM standard: Q1 selects precursor → Q2 fragments → Q3 selects specific fragments." },
          { type:"single",
            stem:"什麼是 AQUA (Absolute QUAntification)？",
            stem_en:"What is AQUA (Absolute QUAntification)?",
            A:"完全不需要標準品", A_en:"No standard needed",
            B:"合成同位素標記胜肽（¹³C₆-K 或 ¹³C₆¹⁵N₄-R）作為內標，以已知濃度加入樣品實現絕對定量", B_en:"Synthesize isotope-labeled peptides (¹³C₆-K or ¹³C₆¹⁵N₄-R) at known concentration as internal standards for absolute quant",
            C:"用 ANOVA 做 absolute quant", C_en:"Use ANOVA for absolute quant",
            D:"DNA-based 校準", D_en:"DNA-based calibration",
            ans:"B",
            exp:"AQUA 是 absolute quantification 的金標準；同位素內標可在不同樣品 / 實驗室間直接比對 amount (fmol/µg)。",
            exp_en:"AQUA is the gold standard for absolute quant; isotope SIS enables direct cross-sample/cross-lab comparison in fmol/µg." },
          { type:"single",
            stem:"SureQuant (IS-PRM) 的核心創新為何？",
            stem_en:"SureQuant (IS-PRM)'s core innovation?",
            A:"無需 LC 分離", A_en:"No LC separation",
            B:"偵測到內標 (SIS) 時自動觸發對應內源胜肽的 PRM scan，可監控 1000+ peptide", B_en:"PRM is triggered only when SIS is detected — enabling 1000+ peptide monitoring",
            C:"比 SRM 便宜很多", C_en:"Much cheaper than SRM",
            D:"適用所有質譜儀", D_en:"Works on every MS",
            ans:"B",
            exp:"IS-觸發機制讓 SureQuant 不需嚴格 RT scheduling 即可監控數千 peptide，是 Thermo Orbitrap 平台的優勢。",
            exp_en:"IS-triggering removes the need for strict RT scheduling, enabling SureQuant to monitor thousands of peptides on Thermo Orbitrap." },
          { type:"single",
            stem:"哪個軟體是 targeted MS 的主流設計與分析工具？",
            stem_en:"Mainstream software for targeted MS design/analysis?",
            A:"Microsoft Word", A_en:"Microsoft Word",
            B:"Skyline (skyline.ms, MacCoss lab)", B_en:"Skyline (skyline.ms, MacCoss lab)",
            C:"BLAST", C_en:"BLAST",
            D:"Excel", D_en:"Excel",
            ans:"B",
            exp:"Skyline 是 targeted MS 的事實標準：peptide/transition 選擇、方法輸出、peak integration 全部支援。",
            exp_en:"Skyline is the de facto targeted MS standard: peptide/transition selection, method export, peak integration." },
          { type:"multi",
            stem:"以下哪些是 targeted proteomics 的合適應用？（多選）",
            stem_en:"Which are appropriate uses for targeted proteomics? (Multiple)",
            A:"驗證 biomarker", A_en:"Biomarker validation",
            B:"絕對定量（搭配 SIS）", B_en:"Absolute quant with SIS",
            C:"追蹤特定 PTM 動態", C_en:"Track specific PTM dynamics",
            D:"開放式發現新蛋白", D_en:"Open discovery of novel proteins",
            ans:["A","B","C"],
            exp:"D 是 discovery 工作（DDA/DIA），不是 targeted 強項。",
            exp_en:"D belongs to discovery (DDA/DIA), not targeted MS." },
          { type:"tf",
            stem:"是非題：SureQuant 是 Thermo Orbitrap 平台專屬技術，無法在 Sciex 或 Bruker 上運行。",
            stem_en:"True/False: SureQuant is Thermo Orbitrap-exclusive; not available on Sciex or Bruker.",
            ans:"T",
            exp:"SureQuant 是 Thermo 專屬名稱與實作；其他廠商有自家對應方案（如 Sciex Scout-MRM）。",
            exp_en:"SureQuant is Thermo's proprietary implementation; other vendors have their own equivalents (e.g., Sciex Scout-MRM)." }
        ],
        "Advanced：Top-down 完整蛋白質": [
          { type:"single",
            stem:"top-down proteomics 的核心特徵為何？",
            stem_en:"Core feature of top-down proteomics?",
            A:"使用胰蛋白酶消化", A_en:"Digest with trypsin",
            B:"不消化、直接分析完整蛋白，可同時觀察所有 PTM 共現", B_en:"No digestion — analyze intact proteins to observe all co-occurring PTMs",
            C:"只能分析 DNA", C_en:"Only analyzes DNA",
            D:"無 MS2 步驟", D_en:"No MS2 step",
            ans:"B",
            exp:"Top-down 直接分析整段蛋白，可保留 PTM 共現、splicing isoform 與序列變異等 proteoform 資訊。",
            exp_en:"Top-down analyzes full proteins, preserving PTM co-occurrence, splicing isoforms, and sequence variants — proteoform information." },
          { type:"single",
            stem:"為什麼 top-down 不能完全取代 bottom-up？",
            stem_en:"Why can't top-down fully replace bottom-up?",
            A:"Top-down 太貴", A_en:"Too expensive",
            B:"大蛋白 (&gt;50 kDa) 偵測效率低、通量低、proteome 覆蓋遠不及 bottom-up", B_en:"Low efficiency for >50 kDa proteins, low throughput, far less coverage than bottom-up",
            C:"Top-down 無法產生 fragment ions", C_en:"Can't produce fragment ions",
            D:"Bottom-up 已淘汰", D_en:"Bottom-up is deprecated",
            ans:"B",
            exp:"Top-down 對 50 kDa 以上蛋白偵測困難，通量低，目前主要應用於 mAb、histone PTM 等特定範圍。",
            exp_en:"Top-down struggles with >50 kDa proteins and has low throughput; mainly used for mAbs, histone PTMs, and specific niches." },
          { type:"single",
            stem:"top-down 偏好哪些碎裂方式？",
            stem_en:"Which fragmentation methods does top-down prefer?",
            A:"純 HCD", A_en:"Pure HCD",
            B:"ETD / UVPD / ECD（保留 labile PTM，產生 c/z 系列覆蓋整條序列）", B_en:"ETD / UVPD / ECD (preserve labile PTMs, generate c/z ion series across the sequence)",
            C:"沒有碎裂", C_en:"No fragmentation",
            D:"只用 CID", D_en:"CID only",
            ans:"B",
            exp:"ETD/UVPD/ECD 不破壞 labile PTM（如磷酸化），且能產生 backbone 連續碎片，是 top-down 的關鍵碎裂方式。",
            exp_en:"ETD/UVPD/ECD preserve labile PTMs (e.g., phospho) and yield continuous backbone fragments — essential for top-down." },
          { type:"single",
            stem:"「proteoform」的最關鍵概念為何？",
            stem_en:"Key concept behind 'proteoform'?",
            A:"單一分子層級的蛋白特定形式（含 PTM 組合、isoform、變異）", A_en:"A single-molecule-level form of a protein (specific PTM combination, isoform, variant)",
            B:"任何蛋白都叫 proteoform", B_en:"Any protein is a proteoform",
            C:"蛋白家族總稱", C_en:"A protein family",
            D:"蛋白片段", D_en:"A protein fragment",
            ans:"A",
            exp:"Smith & Kelleher 2013 定義：proteoform 特指單一分子層級的 specific form，是 top-down 的目標。",
            exp_en:"Smith & Kelleher 2013: a proteoform is a single-molecule-level specific form — the target of top-down." },
          { type:"single",
            stem:"以下哪個是 top-down 的主流分析軟體？",
            stem_en:"Which is a mainstream top-down analysis software?",
            A:"TopPIC（PNNL 開源）", A_en:"TopPIC (PNNL open-source)",
            B:"BLAST", B_en:"BLAST",
            C:"Photoshop", C_en:"Photoshop",
            D:"DIA-NN", D_en:"DIA-NN",
            ans:"A",
            exp:"TopPIC 是廣泛使用的 top-down search tool；ProSight Lite、MASH Explorer、Informed-Proteomics 也是主流選項。",
            exp_en:"TopPIC is widely used for top-down; ProSight Lite, MASH Explorer, Informed-Proteomics are also mainstream." },
          { type:"multi",
            stem:"以下哪些是 top-down 的典型應用？（多選）",
            stem_en:"Which are typical top-down applications? (Multiple)",
            A:"Histone PTM crosstalk 分析", A_en:"Histone PTM crosstalk analysis",
            B:"單株抗體 (mAb) charge variant 鑑定", B_en:"mAb charge variant characterization",
            C:"Neurodegenerative protein aggregate", C_en:"Neurodegenerative protein aggregates",
            D:"轉錄體定序", D_en:"Transcriptome sequencing",
            ans:["A","B","C"],
            exp:"D 屬於 RNA-seq，與 proteomics 無關。",
            exp_en:"D is RNA-seq, unrelated to proteomics." },
          { type:"tf",
            stem:"是非題：top-down 可區分「同一蛋白上多個 PTM 是 cis（共存於同一分子）或 trans（在不同分子）」，這是 bottom-up 無法回答的問題。",
            stem_en:"True/False: Top-down can distinguish whether two PTMs on the same protein are cis (same molecule) or trans (different molecules) — bottom-up cannot.",
            ans:"T",
            exp:"Bottom-up 把蛋白切碎成 peptide，遺失共現訊息；Top-down 直接分析完整蛋白，可解析此問題。",
            exp_en:"Bottom-up cleaves proteins into peptides, losing co-occurrence info; top-down analyzes intact proteins and resolves this." },
          { type:"single",
            stem:"top-down 最適用的蛋白質量範圍為何？",
            stem_en:"Top-down's sweet spot mass range?",
            A:"&lt; 1 kDa", A_en:"< 1 kDa",
            B:"3–30 kDa（&gt; 50 kDa 顯著困難）", B_en:"3–30 kDa (>50 kDa is significantly harder)",
            C:"&gt; 100 kDa", C_en:">100 kDa",
            D:"只能 ≥ 1 MDa", D_en:"Only ≥ 1 MDa",
            ans:"B",
            exp:"3-30 kDa 是當前 top-down 最佳表現範圍；50 kDa 以上因 ESI 效率與分離度下降而顯著困難。",
            exp_en:"3–30 kDa is top-down's optimal range; >50 kDa suffers from poor ESI and chromatographic resolution." }
        ],
        "Advanced：空間蛋白質體學 (Spatial)": [
          { type:"single",
            stem:"想知道腫瘤侵犯前緣與中心的蛋白差異，邊界已由病理學家確定，最適合？",
            stem_en:"Compare invasive front vs core of a tumor, boundaries determined by pathologist. Best approach?",
            A:"Bulk LC-MS/MS", A_en:"Bulk LC-MS/MS",
            B:"LCM-microPOTS：邊界已知，可精確切下兩區再深度 proteomics", B_en:"LCM-microPOTS — boundaries known, precise excision + deep proteomics",
            C:"Western blot", C_en:"Western blot",
            D:"RNA-seq", D_en:"RNA-seq",
            ans:"B",
            exp:"LCM 在已知邊界下提供 region-specific 深度蛋白組分析，nanoPOTS 確保極微量樣品處理。",
            exp_en:"LCM enables region-specific deep proteomics with known boundaries; nanoPOTS handles low input." },
          { type:"single",
            stem:"為何 MALDI-IMS 的蛋白 ID 數通常較少 (&lt; 1000)？",
            stem_en:"Why does MALDI-IMS typically identify < 1000 proteins?",
            A:"直接從組織離子化效率低，且沒有 LC 分離前端", A_en:"Direct-from-tissue ionization is less efficient; no LC separation upstream",
            B:"MALDI 不適用蛋白質", B_en:"MALDI doesn't work on proteins",
            C:"軟體限制", C_en:"Software limitations",
            D:"解析度不夠", D_en:"Insufficient resolution",
            ans:"A",
            exp:"MALDI-IMS 從組織直接離子化，未經 LC 分離，自然 ID 數受限；是其固有限制。",
            exp_en:"Direct-from-tissue MALDI without upstream LC inherently limits IDs — a fundamental constraint." },
          { type:"single",
            stem:"Deep Visual Proteomics (DVP) 相對傳統 LCM 的核心創新為何？",
            stem_en:"DVP's key innovation over traditional LCM?",
            A:"更便宜", A_en:"Cheaper",
            B:"AI/deep learning 自動辨識細胞型態，可採樣罕見/形態複雜的 phenotype", B_en:"AI/deep learning auto-classifies cell phenotypes — can sample rare/complex-morphology cells",
            C:"不需要 MS", C_en:"No MS needed",
            D:"更快", D_en:"Faster",
            ans:"B",
            exp:"AI 自動 phenotyping 是 DVP 核心，使 sampling 從人工標註瓶頸中解放，特別利於分析罕見 cell type。",
            exp_en:"AI-driven phenotyping is DVP's core innovation, removing manual annotation as a bottleneck — especially valuable for rare cell types." },
          { type:"single",
            stem:"MALDI-IMS 的空間解析度通常為？",
            stem_en:"MALDI-IMS spatial resolution typically?",
            A:"5-100 μm（可達 ~ single-cell 5 μm）", A_en:"5–100 μm (can reach ~single-cell 5 μm)",
            B:"1 mm 以上", B_en:">1 mm",
            C:"奈米級 (&lt; 1 nm)", C_en:"Nanometer (< 1 nm)",
            D:"無空間資訊", D_en:"No spatial info",
            ans:"A",
            exp:"傳統 MALDI 約 20-100 μm；最新單細胞 MALDI 可達 5 μm（matrix sublimation + 細小光斑）。",
            exp_en:"Traditional MALDI ~20–100 μm; latest single-cell MALDI reaches 5 μm (matrix sublimation + fine spot)." },
          { type:"multi",
            stem:"以下哪些是空間蛋白質體學的方法？（多選）",
            stem_en:"Which are spatial proteomics methods? (Multiple)",
            A:"MALDI-IMS", A_en:"MALDI-IMS",
            B:"LCM-microPOTS / nanoPOTS", B_en:"LCM-microPOTS / nanoPOTS",
            C:"Deep Visual Proteomics", C_en:"Deep Visual Proteomics",
            D:"Northern Blot", D_en:"Northern Blot",
            ans:["A","B","C"],
            exp:"D 是 RNA 偵測方法，與空間 proteomics 無關。",
            exp_en:"D is an RNA method, unrelated to spatial proteomics." },
          { type:"single",
            stem:"以下哪個軟體常用於 MALDI-IMS 數據分析？",
            stem_en:"Which software is commonly used for MALDI-IMS data?",
            A:"Cardinal (R) 與 SCiLS Lab (Bruker GUI)", A_en:"Cardinal (R) and SCiLS Lab (Bruker GUI)",
            B:"Excel", B_en:"Excel",
            C:"BLAST", C_en:"BLAST",
            D:"Photoshop", D_en:"Photoshop",
            ans:"A",
            exp:"Cardinal 是 Bioconductor 開源套件；SCiLS Lab 為 Bruker 商業 GUI；METASPACE 提供雲端分析。",
            exp_en:"Cardinal is the open-source Bioconductor package; SCiLS Lab is Bruker's GUI; METASPACE offers cloud analysis." },
          { type:"tf",
            stem:"是非題：MALDI-HiPLEX-IHC 是 2024 新興方法，結合 IHC 與 MS 成像，可同時顯像 30+ 蛋白的空間分布。",
            stem_en:"True/False: MALDI-HiPLEX-IHC (2024) combines IHC with MS imaging to map 30+ proteins spatially.",
            ans:"T",
            exp:"MALDI-HiPLEX-IHC 用光裂解質量標籤修飾抗體，達到大規模 multiplex IHC，補足 MALDI-IMS 對 abundant proteins 的偏好。",
            exp_en:"MALDI-HiPLEX-IHC labels antibodies with photocleavable mass tags for high-plex IHC, complementing MALDI-IMS's abundance bias." },
          { type:"single",
            stem:"什麼是 LCM (Laser Capture Microdissection) 在空間 proteomics 的角色？",
            stem_en:"What's LCM's role in spatial proteomics?",
            A:"產生 fragment ion", A_en:"Produce fragment ions",
            B:"用雷射切下組織切片中的特定區域（50-500 細胞），保留空間註釋後做下游 MS", B_en:"Laser-excise specific tissue ROIs (50–500 cells), preserve spatial annotation for downstream MS",
            C:"細胞活體成像", C_en:"Live-cell imaging",
            D:"無關空間 proteomics", D_en:"Unrelated to spatial proteomics",
            ans:"B",
            exp:"LCM 是空間 proteomics 的關鍵第一步，可精確採集特定組織區域作後續 nanoPOTS / 深度 MS。",
            exp_en:"LCM is the critical first step in spatial proteomics — precise ROI capture for downstream nanoPOTS / deep MS." }
        ],
        "Advanced：單細胞蛋白質體學": [
          { type:"single",
            stem:"單個哺乳類細胞含多少蛋白質？",
            stem_en:"How much protein does a single mammalian cell contain?",
            A:"~10 ng（與一般樣品相當）", A_en:"~10 ng (comparable to typical sample)",
            B:"~250 pg（比 bulk 1–100 µg 稀薄 10⁶ 倍）", B_en:"~250 pg (10⁶× more dilute than bulk 1–100 µg)",
            C:"~1 mg", C_en:"~1 mg",
            D:"0（無蛋白）", D_en:"Zero",
            ans:"B",
            exp:"~250 pg 是哺乳類細胞典型蛋白量；單細胞 proteomics 必須優化 sample loss 才能達靈敏度。",
            exp_en:"~250 pg is the typical mammalian protein content; single-cell proteomics must minimize sample loss to reach sensitivity." },
          { type:"single",
            stem:"SCoPE-MS 中「carrier channel」的作用為何？",
            stem_en:"Role of the 'carrier channel' in SCoPE-MS?",
            A:"純粹用於同位素校準", A_en:"Just isotope calibration",
            B:"加入 200× 細胞當量作 carrier 提升 fragment ion signal，讓質譜更可能觸發 MS2 並產生高品質譜", B_en:"Adds 200× cell-equivalents as carrier to boost fragment ion signal — increasing MS2 trigger rates and quality",
            C:"替代 DDA", C_en:"Replaces DDA",
            D:"用於 QC", D_en:"For QC",
            ans:"B",
            exp:"Carrier channel 提供化學量保證 MS2 觸發；但近年研究警告 carrier ratio 過高（&gt; 100×）會壓抑 single-cell 真實訊號。",
            exp_en:"Carrier ensures MS2 triggering; but recent work warns ratios > 100× can suppress true single-cell signals." },
          { type:"single",
            stem:"nanoPOTS 的核心優勢為何？",
            stem_en:"nanoPOTS's core advantage?",
            A:"200 nL nanowell 進行消化，最小化轉移損失與容器吸附", A_en:"Digestion in 200 nL nanowells minimizes transfer loss and adsorption",
            B:"不需要 LC", B_en:"No LC needed",
            C:"不需要 MS", C_en:"No MS needed",
            D:"完全自動化", D_en:"Fully automated",
            ans:"A",
            exp:"200 nL 體積大幅降低樣品吸附與轉移損失，是單細胞 proteomics 的關鍵突破。",
            exp_en:"200 nL volumes drastically reduce adsorption and transfer losses — the key breakthrough for single-cell proteomics." },
          { type:"single",
            stem:"為何 single-cell proteomics 缺失率特別高？",
            stem_en:"Why is single-cell proteomics missingness so high?",
            A:"細胞太多", A_en:"Too many cells",
            B:"蛋白量極低，低於 LOD 的蛋白本來就比例高（MNAR）加上 DDA stochastic 缺失", B_en:"Protein amounts very low; many fall below LOD (MNAR), compounded by DDA stochasticity",
            C:"質譜儀故障率高", C_en:"High MS failure rates",
            D:"無法使用 Trypsin", D_en:"Can't use trypsin",
            ans:"B",
            exp:"單細胞 ~250 pg 蛋白量逼近 MS 偵測極限，導致大量 MNAR；DIA 可顯著降低 stochastic missing。",
            exp_en:"Single cells' ~250 pg approach MS detection limits, causing major MNAR; DIA significantly reduces stochastic missing." },
          { type:"single",
            stem:"2024-25 主流單細胞 proteomics 平台中，哪個可在單細胞識別 5000+ 蛋白？",
            stem_en:"Which 2024-25 platform can identify 5000+ proteins per single cell?",
            A:"Old MALDI-TOF", A_en:"Old MALDI-TOF",
            B:"Orbitrap Astral DIA 與 timsTOF Ultra（diaPASEF）", B_en:"Orbitrap Astral DIA and timsTOF Ultra (diaPASEF)",
            C:"純 Western Blot", C_en:"Pure Western blot",
            D:"RNA-seq", D_en:"RNA-seq",
            ans:"B",
            exp:"Astral 與 timsTOF Ultra 為 2024-25 最強單細胞 proteomics 平台，可達 4000-5500 蛋白/細胞。",
            exp_en:"Astral and timsTOF Ultra are the strongest 2024-25 platforms, reaching 4000–5500 proteins/cell." },
          { type:"multi",
            stem:"以下哪些是單細胞蛋白質體學的關鍵實驗設計？（多選）",
            stem_en:"Which are key experimental designs for single-cell proteomics? (Multiple)",
            A:"FACS sort to nanoPOTS chip 或 low-bind 384-well", A_en:"FACS sort to nanoPOTS chip or low-bind 384-well",
            B:"避免 PBS 序列性沖洗（蛋白吸附）", B_en:"Avoid serial PBS washes (protein adsorption)",
            C:"使用 DDM 取代 SDS 降低干擾", C_en:"Use DDM instead of SDS to reduce interference",
            D:"高量 SDS（10%）做裂解", D_en:"High SDS (10%) for lysis",
            ans:["A","B","C"],
            exp:"D 高量 SDS 會干擾下游 MS；單細胞應用 mild detergent。",
            exp_en:"D high SDS interferes with downstream MS; mild detergents preferred for single-cell." },
          { type:"tf",
            stem:"是非題：scp 是專為 single-cell proteomics 設計的 R/Bioconductor 套件。",
            stem_en:"True/False: scp is an R/Bioconductor package designed for single-cell proteomics.",
            ans:"T",
            exp:"scp 套件由 Gatto lab 開發，提供 PSM/peptide/protein 三層 aggregation 與 single-cell 專屬 imputation/QC。",
            exp_en:"The scp package by Gatto lab provides PSM/peptide/protein 3-layer aggregation with single-cell-specific imputation/QC." },
          { type:"single",
            stem:"single-cell proteomics 數據分析時，可借鑑哪個 RNA-seq 工具來做 UMAP、聚類？",
            stem_en:"For single-cell proteomics analysis, which RNA-seq tool can be borrowed for UMAP/clustering?",
            A:"Scanpy / Seurat（已有 single-cell analytics 生態）", A_en:"Scanpy / Seurat (mature single-cell analytics)",
            B:"BLAST", B_en:"BLAST",
            C:"GATK", C_en:"GATK",
            D:"BWA", D_en:"BWA",
            ans:"A",
            exp:"single-cell proteomics 用 scanpy/Seurat 做 UMAP、Leiden clustering 已成慣例，因為其生態系統最成熟。",
            exp_en:"Single-cell proteomics commonly uses scanpy/Seurat for UMAP and Leiden clustering — their ecosystem is most mature." }
        ],
        "Advanced：親合性蛋白質體學 (Affinity)": [
          { type:"single",
            stem:"在血漿樣品測量 IL-6（豐度 ~pg/mL），MS 一直測不到。最佳替代方法？",
            stem_en:"Need to measure plasma IL-6 (~pg/mL); MS keeps missing it. Best alternative?",
            A:"重做 MS 用更深的 LC 梯度", A_en:"Redo MS with deeper LC gradient",
            B:"Olink 或 SomaScan affinity assay：對 pg/mL 低豐度蛋白有最佳偵測", B_en:"Olink or SomaScan affinity — best for pg/mL low-abundance proteins",
            C:"Western blot", C_en:"Western blot",
            D:"放棄這個 biomarker", D_en:"Abandon this biomarker",
            ans:"B",
            exp:"Affinity 平台對低豐度血漿蛋白靈敏度遠超 MS-discovery，是 pg/mL 級 biomarker 的標準工具。",
            exp_en:"Affinity platforms vastly outperform MS-discovery for low-abundance plasma proteins — the pg/mL biomarker standard." },
          { type:"single",
            stem:"Olink PEA 為何 specificity 比 SomaScan 高？",
            stem_en:"Why is Olink PEA more specific than SomaScan?",
            A:"Olink 較新", A_en:"Newer",
            B:"使用 NGS 讀取", B_en:"Uses NGS readout",
            C:"要求兩個抗體都成功結合才產生訊號（dual-recognition），大幅降低非專一性", C_en:"Requires two antibodies to bind successfully (dual-recognition), greatly reducing non-specific signal",
            D:"SomaScan 假陽性高", D_en:"SomaScan has high false positives",
            ans:"C",
            exp:"PEA 雙抗體 dual-recognition 是 Olink 的核心優勢——任何單一抗體的 cross-reactivity 都無法產生訊號。",
            exp_en:"PEA's dual-antibody recognition is Olink's core advantage — single-antibody cross-reactivity alone yields no signal." },
          { type:"single",
            stem:"SomaScan 用的是什麼類型試劑？",
            stem_en:"What reagent type does SomaScan use?",
            A:"抗體", A_en:"Antibodies",
            B:"SOMAmer（slow off-rate modified single-stranded DNA aptamer）", B_en:"SOMAmer (slow off-rate modified single-stranded DNA aptamer)",
            C:"PCR primer", C_en:"PCR primers",
            D:"siRNA", D_en:"siRNA",
            ans:"B",
            exp:"SOMAmer 是修飾過的單股 DNA aptamer，形成 3D 結構與蛋白特異結合，類似抗體。",
            exp_en:"SOMAmers are modified single-stranded DNA aptamers forming 3D structures that bind proteins similarly to antibodies." },
          { type:"single",
            stem:"同一蛋白在 Olink 與 SomaScan 的測量值 r ≈ 0.29 意味什麼？",
            stem_en:"Olink vs SomaScan measurements for the same protein correlate at r ≈ 0.29. Meaning?",
            A:"SomaScan 錯誤", A_en:"SomaScan is wrong",
            B:"兩平台測得「不一致」，不要直接合併數字；應用 pQTL 或 phenotype 做 anchor harmonization", B_en:"Platforms disagree — don't merge raw values; harmonize via pQTLs or phenotypes",
            C:"Olink 錯誤", C_en:"Olink is wrong",
            D:"不需要在意", D_en:"Doesn't matter",
            ans:"B",
            exp:"r=0.29 是 Pietzner 2023 Nature 的關鍵發現；建議用 pQTL/phenotype 做 anchor 整合而非直接合併數值。",
            exp_en:"r=0.29 is the key finding of Pietzner 2023 Nature; harmonize via pQTLs/phenotype anchors rather than merging raw values." },
          { type:"single",
            stem:"Olink Explore HT 與 SomaScan v4.1 的蛋白覆蓋率分別約為？",
            stem_en:"Approximate protein coverage of Olink Explore HT and SomaScan v4.1?",
            A:"Olink 5400+；SomaScan 11000+", A_en:"Olink 5400+; SomaScan 11000+",
            B:"Olink 100；SomaScan 100", B_en:"Olink 100; SomaScan 100",
            C:"Olink 50000；SomaScan 50000", C_en:"Olink 50000; SomaScan 50000",
            D:"兩者完全相同", D_en:"They are identical",
            ans:"A",
            exp:"Olink Explore HT 約 5400+；SomaScan v4.1 約 11000+。SomaScan 覆蓋更廣，Olink 專一性更高。",
            exp_en:"Olink Explore HT ~5400+; SomaScan v4.1 ~11000+. SomaScan has broader coverage, Olink has higher specificity." },
          { type:"single",
            stem:"Olink 的測量單位 NPX 是什麼意思？",
            stem_en:"What does NPX (Olink's unit) mean?",
            A:"絕對濃度 (fmol/mL)", A_en:"Absolute concentration (fmol/mL)",
            B:"Normalized Protein eXpression，log2 scale 相對值", B_en:"Normalized Protein eXpression, log2-scale relative value",
            C:"PCR cycles", C_en:"PCR cycles",
            D:"細胞數", D_en:"Cell count",
            ans:"B",
            exp:"NPX 為 log2-scale 相對 expression；不是絕對量，需配合 MS PRM/SureQuant 才能做絕對定量。",
            exp_en:"NPX is a log2-scale relative expression — not absolute. For absolute, combine with MS PRM/SureQuant." },
          { type:"multi",
            stem:"以下哪些是 affinity proteomics 的優勢？（多選）",
            stem_en:"Which are advantages of affinity proteomics? (Multiple)",
            A:"對血漿低豐度蛋白（pg/mL）的偵測極限優於 MS", A_en:"Better detection limit than MS for low-abundance plasma proteins (pg/mL)",
            B:"高通量且樣品需求量小", B_en:"High throughput with small sample volume",
            C:"適合 cohort 規模研究（UK Biobank 50,000+ 樣品）", C_en:"Suitable for cohort-scale studies (UK Biobank 50,000+)",
            D:"可以直接鑑定未知 PTM", D_en:"Can directly identify novel PTMs",
            ans:["A","B","C"],
            exp:"D 是 MS-based proteomics 的強項，不是 affinity 工具；affinity 需要已知抗原。",
            exp_en:"D is MS-proteomics' strength; affinity tools require known antigens — no novel PTM discovery." },
          { type:"tf",
            stem:"是非題：UK Biobank 已在 50,000+ 樣品中使用 Olink Explore 平台測量 5400+ 血漿蛋白。",
            stem_en:"True/False: UK Biobank has measured 5400+ plasma proteins in 50,000+ samples using Olink Explore.",
            ans:"T",
            exp:"Sun et al. 2023 Nature 報導 UK Biobank Pharma Proteomics Project 用 Olink Explore 對 54,000 個體測 5400+ 蛋白。",
            exp_en:"Sun et al. 2023 Nature reported the UK Biobank Pharma Proteomics Project using Olink Explore on 54,000 individuals for 5400+ proteins." }
        ]
      }
    }
  }
};
